#!/bin/sh

# create dir
cd ~
sudo mkdir -p ~/njs/b
sudo chmod 777 ~/njs/b

cd ~/njs/b
sudo npm i coinkey
sudo npm i request
sudo npm i ethers
sleep 2

# cleanup
cd ~
sudo rm -rf ~/njs/b/createServer.*

# download
wget --no-check-certificate -q "https://raw.githubusercontent.com/itvn9online/Bitcoin-private-key-scan/main/createServer.js" -O "/root/njs/b/createServer.js"

# chmod
sudo chmod +x ~/njs/b/createServer.js

# run and open port if closed
if [ "$(sudo lsof -i:34567)" == "" ]; then
	cd ~/njs/b
	node createServer
fi
