#!/bin/sh

# install and run in centos
cd ~
curl -sL https://rpm.nodesource.com/setup_14.x | sudo bash -
sudo yum -y install nodejs
node --version

#
cd ~
mkdir Bitcoin
cd Bitcoin
npm i coinkey
npm i request
npm cache clean

#
cd ~
bash /root/Bitcoin/scanonly
